name: flutter_template
description: A responsive Flutter login screen

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_framework: ^1.5.1
  flutter_svg: ^2.0.17
  adaptive_theme: ^3.7.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/